### ISSUE TITLE
I MISS SKALNIK

### ISSUE THREAD

**Issue by brandon-beacher** [skalnik/joubini#1]
Plz to fix?

**Comment by skalnik** [comment]
Hi Brandon. I am eating a beehive right now!

**Comment by brandon-beacher** [comment]
NO YOU ARE NOT! really? :bee:

**Comment by skalnik** [comment]
![photo on 1-6-15 at 10 20 am](https://cloud.githubusercontent.com/assets/2546/5633573/ba8f0f66-958d-11e4-8686-97a55eb9dd49.jpg)

**Comment by brandon-beacher** [comment]
JEALOUS. This is my new favorite photo. Old favorite is:
![9312409073_557fc9afed_z](https://cloud.githubusercontent.com/assets/469/5633801/b1fbb3f2-95a8-11e4-8234-af26f11932ab.jpg)

**Comment by skalnik** [comment]
I'm going to go ahead and close this unless you've got something more actionable to help me alleviate your pain.
